server {
  listen 80;

  root /usr/share/nginx/html;

  index index.html;

  location ~ \.css {
      access_log          off;
      expires             1M;
      add_header          Content-Type        text/css;
      add_header          Cache-Control       "public";
      try_files $uri $uri/ =404;
  }

  location ~ \.js {
      access_log          off;
      expires             1M;
      add_header          Content-Type        application/x-javascript;
      add_header          Cache-Control       "public";
      try_files $uri $uri/ =404;
  }

  location ~* \.(?:jpg|jpeg|gif|png|ico|cur|gz|svg|svgz|mp4|ogg|ogv|webm|htc|woff|woff2)$ {
      access_log          off;
      expires             1M;
      add_header          Cache-Control       "public";
      try_files $uri $uri/ =404;
  }

  location / {
      rewrite ^/(.*) /index.html break;
      try_files $uri $uri/ =404;
  }
}
